"""Convert each rule to every backend and write the queries next to the rules.

Committed output is reviewable in a diff. A conversion that only ever runs in
CI is a claim nobody can read, and a query that silently changes shape between
pySigma versions is worth seeing in a pull request.

    python -m scripts.convert_rules            write rules/converted/
    python -m scripts.convert_rules --check    fail if committed output is stale
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = REPO_ROOT / "rules"
OUT_DIR = RULES_DIR / "converted"

# backend name to file extension. both pinned in requirements.txt.
BACKENDS = {"splunk": "spl", "kusto": "kql"}
PIPELINES = ("sysmon", "windows-logsources")

HEADER = (
    "// generated by scripts/convert_rules.py, do not edit\n"
    "// source: {source}\n"
    "// backend: {backend}, pipelines: {pipelines}\n"
)


def convert(rule: Path, backend: str, sigma: str) -> str:
    cmd = [sigma, "convert", "-t", backend]
    for pipeline in PIPELINES:
        cmd += ["-p", pipeline]
    cmd.append(str(rule))
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)
    if proc.returncode != 0:
        raise RuntimeError(f"{rule.name} -> {backend} failed: {proc.stderr.strip()}")
    # sigma-cli prints a progress line before the query itself
    lines = [ln for ln in proc.stdout.splitlines()
             if ln.strip() and not ln.startswith("Parsing Sigma rules")]
    return "\n".join(lines).strip() + "\n"


def build(sigma: str) -> dict[Path, str]:
    out: dict[Path, str] = {}
    for rule in sorted(RULES_DIR.glob("*.yml")):
        for backend, extension in BACKENDS.items():
            body = convert(rule, backend, sigma)
            header = HEADER.format(
                source=f"rules/{rule.name}", backend=backend,
                pipelines=" + ".join(PIPELINES),
            )
            out[OUT_DIR / f"{rule.stem}.{extension}"] = header + body
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="convert rules to each backend")
    parser.add_argument("--check", action="store_true",
                        help="fail if committed queries differ from a fresh conversion")
    parser.add_argument("--sigma", default="sigma", help="path to the sigma cli")
    args = parser.parse_args(argv)

    generated = build(args.sigma)

    if args.check:
        stale = []
        for path, body in generated.items():
            if not path.exists():
                stale.append(f"{path.relative_to(REPO_ROOT)}: missing")
            elif path.read_text() != body:
                stale.append(f"{path.relative_to(REPO_ROOT)}: differs")
        committed = {p for p in OUT_DIR.glob("*") if p.is_file()} if OUT_DIR.exists() else set()
        for path in sorted(committed - set(generated)):
            stale.append(f"{path.relative_to(REPO_ROOT)}: no longer generated")
        if stale:
            print("converted queries are stale:", file=sys.stderr)
            for line in stale:
                print(f"  {line}", file=sys.stderr)
            print("regenerate with: python -m scripts.convert_rules", file=sys.stderr)
            return 1
        print(f"{len(generated)} converted queries match a fresh conversion")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, body in generated.items():
        path.write_text(body)
    print(f"wrote {len(generated)} queries to {OUT_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
